apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-service
          image: order-grpc-service:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
          env:
            - name: APPLICATION_PORT
              value: "8080"
            - name: ENV
              value: "prod"
            - name: DATA_SOURCE_URL
              value: "root:password@tcp(mysql:3306)/order?charset=utf8mb4&parseTime=true&loc=Local&tls=skip-verify"
            - name: PAYMENT_SERVICE_URL
              value: "payment:8081"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - order.ingress.local
      secretName: order-tls
  rules:
    - host: order.ingress.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: order
                port:
                  number: 8080
