apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment-service
          image: payment-grpc-service:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
          env:
            - name: APPLICATION_PORT
              value: "8081"
            - name: ENV
              value: "prod"
            - name: DATA_SOURCE_URL
              value: "root:password@tcp(mysql:3306)/payment?charset=utf8mb4&parseTime=true&loc=Local&tls=skip-verify"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - payment.ingress.local
      secretName: payment-tls
  rules:
    - host: payment.ingress.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment
                port:
                  number: 8081
